// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITest.Input;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WindowsRuntimeControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = Microsoft.VisualStudio.TestTools.UITest.Input.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26621.2")]
    public partial class UIMap
    {
        
        #region Properties
        public UIStartWindow UIStartWindow
        {
            get
            {
                if ((this.mUIStartWindow == null))
                {
                    this.mUIStartWindow = new UIStartWindow();
                }
                return this.mUIStartWindow;
            }
        }
        
        public UIMyWeatherAppUWPWindow UIMyWeatherAppUWPWindow
        {
            get
            {
                if ((this.mUIMyWeatherAppUWPWindow == null))
                {
                    this.mUIMyWeatherAppUWPWindow = new UIMyWeatherAppUWPWindow();
                }
                return this.mUIMyWeatherAppUWPWindow;
            }
        }
        
        public UIMyWeatherAppUWPWindow1 UIMyWeatherAppUWPWindow1
        {
            get
            {
                if ((this.mUIMyWeatherAppUWPWindow1 == null))
                {
                    this.mUIMyWeatherAppUWPWindow1 = new UIMyWeatherAppUWPWindow1();
                }
                return this.mUIMyWeatherAppUWPWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIStartWindow mUIStartWindow;
        
        private UIMyWeatherAppUWPWindow mUIMyWeatherAppUWPWindow;
        
        private UIMyWeatherAppUWPWindow1 mUIMyWeatherAppUWPWindow1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26621.2")]
    public class UIStartWindow : XamlWindow
    {
        
        public UIStartWindow()
        {
            #region Search Criteria
            this.SearchProperties[XamlControl.PropertyNames.Name] = "Start";
            this.SearchProperties[XamlControl.PropertyNames.ClassName] = "Windows.UI.Core.CoreWindow";
            this.WindowTitles.Add("Start");
            #endregion
        }
        
        #region Properties
        public UIPinnedtilesList UIPinnedtilesList
        {
            get
            {
                if ((this.mUIPinnedtilesList == null))
                {
                    this.mUIPinnedtilesList = new UIPinnedtilesList(this);
                }
                return this.mUIPinnedtilesList;
            }
        }
        #endregion
        
        #region Fields
        private UIPinnedtilesList mUIPinnedtilesList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26621.2")]
    public class UIPinnedtilesList : XamlList
    {
        
        public UIPinnedtilesList(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlList.PropertyNames.AutomationId] = "groupItems";
            this.WindowTitles.Add("Start");
            #endregion
        }
        
        #region Properties
        public UIMyWeatherAppUWPsgrouGroup UIMyWeatherAppUWPsgrouGroup
        {
            get
            {
                if ((this.mUIMyWeatherAppUWPsgrouGroup == null))
                {
                    this.mUIMyWeatherAppUWPsgrouGroup = new UIMyWeatherAppUWPsgrouGroup(this);
                }
                return this.mUIMyWeatherAppUWPsgrouGroup;
            }
        }
        #endregion
        
        #region Fields
        private UIMyWeatherAppUWPsgrouGroup mUIMyWeatherAppUWPsgrouGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26621.2")]
    public class UIMyWeatherAppUWPsgrouGroup : XamlControl
    {
        
        public UIMyWeatherAppUWPsgrouGroup(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Group";
            this.SearchProperties["AutomationId"] = "{773b76b7-cd85-4065-a521-09669ffef016}";
            this.WindowTitles.Add("Start");
            #endregion
        }
        
        #region Properties
        public XamlListItem UIMyWeatherAppUWPListItem
        {
            get
            {
                if ((this.mUIMyWeatherAppUWPListItem == null))
                {
                    this.mUIMyWeatherAppUWPListItem = new XamlListItem(this);
                    #region Search Criteria
                    this.mUIMyWeatherAppUWPListItem.SearchProperties[XamlListItem.PropertyNames.AutomationId] = "tile-P~0d599d98-d9a7-4453-9f7d-b76ccfa9e3b9_2jv79xvh9a28c!App";
                    this.mUIMyWeatherAppUWPListItem.WindowTitles.Add("Start");
                    #endregion
                }
                return this.mUIMyWeatherAppUWPListItem;
            }
        }
        #endregion
        
        #region Fields
        private XamlListItem mUIMyWeatherAppUWPListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26621.2")]
    public class UIMyWeatherAppUWPWindow : XamlWindow
    {
        
        public UIMyWeatherAppUWPWindow()
        {
            #region Search Criteria
            this.TechnologyName = "UIA";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Window";
            this.SearchProperties[UITestControl.PropertyNames.Name] = "MyWeatherApp.UWP";
            this.SearchProperties["FrameworkId"] = "Win32";
            #endregion
        }
        
        #region Properties
        public UIYourLocationsListTabList UIYourLocationsListTabList
        {
            get
            {
                if ((this.mUIYourLocationsListTabList == null))
                {
                    this.mUIYourLocationsListTabList = new UIYourLocationsListTabList(this);
                }
                return this.mUIYourLocationsListTabList;
            }
        }
        
        public UIItemCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new UIItemCustom(this);
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIYourLocationsListTabList mUIYourLocationsListTabList;
        
        private UIItemCustom mUIItemCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26621.2")]
    public class UIYourLocationsListTabList : XamlControl
    {
        
        public UIYourLocationsListTabList(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "TabList";
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Your Locations List";
            this.WindowTitles.Add("MyWeatherApp.UWP");
            #endregion
        }
        
        #region Properties
        public UIXamarinFormsNavigatiTabPage UIXamarinFormsNavigatiTabPage
        {
            get
            {
                if ((this.mUIXamarinFormsNavigatiTabPage == null))
                {
                    this.mUIXamarinFormsNavigatiTabPage = new UIXamarinFormsNavigatiTabPage(this);
                }
                return this.mUIXamarinFormsNavigatiTabPage;
            }
        }
        #endregion
        
        #region Fields
        private UIXamarinFormsNavigatiTabPage mUIXamarinFormsNavigatiTabPage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26621.2")]
    public class UIXamarinFormsNavigatiTabPage : XamlControl
    {
        
        public UIXamarinFormsNavigatiTabPage(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "TabPage";
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Xamarin.Forms.NavigationPage";
            this.WindowTitles.Add("MyWeatherApp.UWP");
            #endregion
        }
        
        #region Properties
        public XamlButton UIAddLocationButton
        {
            get
            {
                if ((this.mUIAddLocationButton == null))
                {
                    this.mUIAddLocationButton = new XamlButton(this);
                    #region Search Criteria
                    this.mUIAddLocationButton.SearchProperties[XamlButton.PropertyNames.AutomationId] = "AddButton";
                    this.mUIAddLocationButton.WindowTitles.Add("MyWeatherApp.UWP");
                    #endregion
                }
                return this.mUIAddLocationButton;
            }
        }
        
        public XamlButton UIDeleteSelectedButton
        {
            get
            {
                if ((this.mUIDeleteSelectedButton == null))
                {
                    this.mUIDeleteSelectedButton = new XamlButton(this);
                    #region Search Criteria
                    this.mUIDeleteSelectedButton.SearchProperties[XamlButton.PropertyNames.AutomationId] = "DeleteButton";
                    this.mUIDeleteSelectedButton.WindowTitles.Add("MyWeatherApp.UWP");
                    #endregion
                }
                return this.mUIDeleteSelectedButton;
            }
        }
        
        public XamlButton UIUpdateWeatherButton
        {
            get
            {
                if ((this.mUIUpdateWeatherButton == null))
                {
                    this.mUIUpdateWeatherButton = new XamlButton(this);
                    #region Search Criteria
                    this.mUIUpdateWeatherButton.SearchProperties[XamlButton.PropertyNames.AutomationId] = "UpdateButton";
                    this.mUIUpdateWeatherButton.WindowTitles.Add("MyWeatherApp.UWP");
                    #endregion
                }
                return this.mUIUpdateWeatherButton;
            }
        }

        public XamlList UIAllLocationsListList
        {
            get
            {
                if ((this.mUIAllLocationsListList == null))
                {
                    this.mUIAllLocationsListList = new XamlList(this);
                    #region Search Criteria
                    this.mUIAllLocationsListList.SearchProperties[XamlList.PropertyNames.AutomationId] = "AllLocationsList";
                    this.mUIAllLocationsListList.WindowTitles.Add("MyWeatherApp.UWP");
                    #endregion
                }
                return this.mUIAllLocationsListList;
            }
        }
        #endregion

        #region Fields
        private XamlButton mUIAddLocationButton;
        
        private XamlButton mUIDeleteSelectedButton;
        
        private XamlButton mUIUpdateWeatherButton;

        private XamlList mUIAllLocationsListList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26621.2")]
    public class UIItemCustom : XamlControl
    {
        
        public UIItemCustom(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Custom";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = null;
            this.WindowTitles.Add("MyWeatherApp.UWP");
            #endregion
        }
        
        #region Properties
        public UIItemCustom1 UIItemCustom1
        {
            get
            {
                if ((this.mUIItemCustom1 == null))
                {
                    this.mUIItemCustom1 = new UIItemCustom1(this);
                }
                return this.mUIItemCustom1;
            }
        }
        
        public XamlList UISearchedItemsListVieList
        {
            get
            {
                if ((this.mUISearchedItemsListVieList == null))
                {
                    this.mUISearchedItemsListVieList = new XamlList(this);
                    #region Search Criteria
                    this.mUISearchedItemsListVieList.SearchProperties[XamlList.PropertyNames.AutomationId] = "SearchedItemsListView";
                    this.mUISearchedItemsListVieList.WindowTitles.Add("MyWeatherApp.UWP");
                    #endregion
                }
                return this.mUISearchedItemsListVieList;
            }
        }                
        #endregion
        
        #region Fields
        private UIItemCustom1 mUIItemCustom1;
        
        private XamlList mUISearchedItemsListVieList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26621.2")]
    public class UIItemCustom1 : XamlControl
    {
        
        public UIItemCustom1(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Custom";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = null;
            this.SearchConfigurations.Add(SearchConfiguration.DisambiguateChild);
            this.WindowTitles.Add("MyWeatherApp.UWP");
            #endregion
        }
        
        #region Properties
        public XamlEdit UIZipCodeEntryEdit
        {
            get
            {
                if ((this.mUIZipCodeEntryEdit == null))
                {
                    this.mUIZipCodeEntryEdit = new XamlEdit(this);
                    #region Search Criteria
                    this.mUIZipCodeEntryEdit.SearchProperties[XamlEdit.PropertyNames.AutomationId] = "zipCodeEntry";
                    this.mUIZipCodeEntryEdit.WindowTitles.Add("MyWeatherApp.UWP");
                    #endregion
                }
                return this.mUIZipCodeEntryEdit;
            }
        }
        
        public XamlButton UISearchAgainButton
        {
            get
            {
                if ((this.mUISearchAgainButton == null))
                {
                    this.mUISearchAgainButton = new XamlButton(this);
                    #region Search Criteria
                    this.mUISearchAgainButton.SearchProperties[XamlButton.PropertyNames.AutomationId] = "getLocationBtn";
                    this.mUISearchAgainButton.WindowTitles.Add("MyWeatherApp.UWP");
                    #endregion
                }
                return this.mUISearchAgainButton;
            }
        }
        #endregion
        
        #region Fields
        private XamlEdit mUIZipCodeEntryEdit;
        
        private XamlButton mUISearchAgainButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26621.2")]
    public class UIMyWeatherAppUWPWindow1 : UITestControl
    {
        
        public UIMyWeatherAppUWPWindow1()
        {
            #region Search Criteria
            this.TechnologyName = "UIA";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Window";
            this.SearchProperties[UITestControl.PropertyNames.Name] = "MyWeatherApp.UWP";
            this.SearchProperties["FrameworkId"] = "Win32";
            #endregion
        }
        
        #region Properties
        public UITestControl UICloseMyWeatherAppUWPButton
        {
            get
            {
                if ((this.mUICloseMyWeatherAppUWPButton == null))
                {
                    this.mUICloseMyWeatherAppUWPButton = new UITestControl(this);
                    #region Search Criteria
                    this.mUICloseMyWeatherAppUWPButton.TechnologyName = "UIA";
                    this.mUICloseMyWeatherAppUWPButton.SearchProperties[UITestControl.PropertyNames.ControlType] = "Button";
                    this.mUICloseMyWeatherAppUWPButton.SearchProperties["AutomationId"] = "Close";
                    #endregion
                }
                return this.mUICloseMyWeatherAppUWPButton;
            }
        }
        #endregion
        
        #region Fields
        private UITestControl mUICloseMyWeatherAppUWPButton;
        #endregion
    }
}
